# Generated by Django 4.1.7 on 2023-03-19 21:07

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', djongo.models.fields.EmbeddedField(model_container=store.models.CarCategory)),
                ('images', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=100)),
                ('type', models.CharField(default='Client', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', djongo.models.fields.ArrayField(model_container=store.models.Car)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('client', djongo.models.fields.ArrayField(model_container=store.models.Client, null=True)),
                ('products', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('detalle', djongo.models.fields.EmbeddedField(model_container=store.models.OrderDetails)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
    ]
